services:
  backend:
    build: python:3.13-slim
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    depends_on:
      - postgres
    restart: always

  postgres:
    # Образ postgres с поддержкой pgvector
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"

volumes:
  postgres-data: {}
