version: '3.8'

services:
  ner-app:
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Для X11 forwarding
    environment:
      - DISPLAY=host.docker.internal:0
      - PYTHONPATH=/app
    network_mode: host
    tty: true
