services:
  backend:
    build: .
    ports:
      - "80:8000"
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  postgres:
    image: postgres:latest
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    env_file:
      - .env
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"

volumes:
  postgres-data: {}
